### ISSUE TITLE
Bug: Test Failure

### ISSUE THREAD

**Issue by mster** [mster/reqi#48]
`test https request`

FAILS with ERROR:
```sh
# test https request
not ok 15 ReqiError: Error: certificate has expired
  ---
    operator: fail
    at: Test.<anonymous> (/home/m/code/node/reqi/tests/integration/test-ssl.js:36:7)
    stack: |-
      Error: ReqiError: Error: certificate has expired
          at Test.assert [as _assert] (/home/m/code/node/reqi/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/home/m/code/node/reqi/node_modules/tape/lib/test.js:80:32)
          at Test.fail (/home/m/code/node/reqi/node_modules/tape/lib/test.js:322:10)
          at Test.bound [as fail] (/home/m/code/node/reqi/node_modules/tape/lib/test.js:80:32)
          at Test.<anonymous> (/home/m/code/node/reqi/tests/integration/test-ssl.js:36:7)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ...
```

**Comment by mster** [comment]
closed by #49
